name: go-fastapi-QC

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v2
        name: setup python environment
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check common spelling errors
        run: poetry run tox -e codespell

      - name: Check code quality with ruff and black
        run: poetry run tox -e lint

      - name: Test with pytest and generate coverage file
        run: poetry run tox -e py
